/***********************************************************************/
/*                                                                     */
/*  FILE        :hwsetup.c                                             */
/*  DATE        :Fri, Aug 12, 2005                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :SH7149                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.0).     */
/*                                                                     */
/***********************************************************************/
#ifndef  _ADProg_C
    #define  _ADProg_C
#endif

#include "ProgHeader.h"

void ADInitCalib(void)
{
    UBYTE i;
    ULONG ul_Itemp1;
    SWORD sw_Itemp, swIAtemp, swICtemp;

    //ULONG ul_Itemp1, ul_Itemp2;                                   //clear Warning, Special.kung, 03/08/2023
    //SWORD sw_Itemp, sw_Itemp1, swIAtemp, swICtemp;                //clear Warning, Special.kung, 03/08/2023
	


    S12ADB0.ADCSR.BIT.ADST = 1;      // A/D start bit
    S12ADB1.ADCSR.BIT.ADST = 1;      // A/D start bit
    AD0.ADCSR.BIT.ADST = 1 ;         // Start 10-bit A/D Scan Conversion Process
    for(i=0;i<64;i++){
#if 1
        //PORTA.PODR.BIT.B0 = 1;
        AN000  = S12ADB0.ADDR0;	// Iu
        AN001  = S12ADB0.ADDR1;	// Iv	
    	AN002  = S12ADB0.ADDR2;	// Iw
    	AN003  = S12ADB0.ADDR3; // dcBus  
    	AN100  = S12ADB1.ADDR0; // GFF_AD, DINO, 03/01/2010
    	AN101  = S12ADB1.ADDR1; // SIN/COS, DINO, 08/12/2010
        AN102  = S12ADB1.ADDR2; // AUI2, IO Define, Bernie, 07/22/2011  
    	AN103  = S12ADB1.ADDR3; // AUI1, IO Define, Bernie, 07/22/2011
       
    	AN00  = (UWORD)(AD0.ADDRA.WORD & 0x3FF); // PGT, PG Type, IO Define, Sean, 06/25/2010
    	AN01  = (UWORD)(AD0.ADDRB.WORD & 0x3FF); // System reference Voltage
    	AN02  = (UWORD)(AD0.ADDRC.WORD & 0x3FF); // TH2, IO Define, Sean, 06/25/2010  HeatSink Temprature
        AN03  = (UWORD)(AD0.ADDRD.WORD & 0x3FF); // TH1, IO Define, Sean, 06/25/2010  IGBT Temprature  
        AN06  = (UWORD)(AD0.ADDRG.WORD & 0x3FF); // [Safty 1, Bernie, 2013/09/06]
    	AN07  = (UWORD)(AD0.ADDRH.WORD & 0x3FF); // [Safty 2, Bernie, 2013/09/06]   
    	AN08  = (UWORD)(AD0.ADDRI.WORD & 0x3FF); // [Safty 3, Bernie, 2013/09/06]           
    	AN09  = (UWORD)(AD0.ADDRJ.WORD & 0x3FF); // [Safty 4, Bernie, 2013/09/06]   
#endif       
		
        /* AD don't shift 6 in SH7147 and it's scale is 12bit. Modify by dino, 2007/01/29 */
        AD_ulIA0 += AN000;
        AD_ulIB0 += AN001;
        AD_ulIC0 += AN002;                
        dcbusAD = AN003;      

        //AN00 = ((ULONG)AN00*4095)>>10;
        AN01 = ((ULONG)AN01*4095)>>10;
        AN02 = ((ULONG)AN02*4095)>>10;
        AN03 = ((ULONG)AN03*4095)>>10;

//---ADDED BY DINO 09/23/2008---
        //------ Calculate PGLOSS ----------------------------------//
        //PGLadLPF reference(AN11) cancelled, replaced w/ PGLOSS, Sean, 01/25/2010
    	//PGLadLPF.sl += (SLONG)( (SWORD)AN11 - PGLadLPF.sw.hi ) * 0x4000;
//---ADDED BY DINO 10/16/2007---
        //------ Calculate Sin_data (SCI4_DIR=1) -------------------//
		SINadLPF.sl += (SLONG)( (SWORD)AN101 - SINadLPF.sw.hi ) * 0x4000;  // SIN/COS, DINO, 08/12/2010
//---END 10/16/2007---------------	
        //------ Calculate TH1 and TH2 ------------------------------//
		TH1adLPF.sl += (SLONG)( (SWORD)AN03 - TH1adLPF.sw.hi ) * 0x4000;	// 100ms (base 1ms), IO Define, Sean, 06/25/2010
		TH2adLPF.sl += (SLONG)( (SWORD)AN02 - TH2adLPF.sw.hi ) * 0x4000;	// 100ms (base 1ms), IO Define, Sean, 06/25/2010
    }


    AD_uwIA0 = AD_ulIA0 >> 2;
    AD_uwIB0 = AD_ulIB0 >> 2;
    AD_uwIC0 = AD_ulIC0 >> 2;

    AD_swIAPu_Old = 0;
    AD_swIBPu_Old = 0;
    AD_swICPu_Old = 0;
    
    /*--------- Calculate Isum from Iu, Iw ---------------------------
    --                                                              --
    -- Isum   = sqrt(2/3(Iu^2+IuIw+Iw^2))				    		--
    --        = sqrt(2/3)*sqrt((Iu+Iw)^2-IuIw)	, Q11				--
    --                                                              --
    -- IrmsAD is 300%/Q12 rated peak current.                       --
    -- sw_Itemp is 250%/Q11 rated rms current.                      --
    -- Therefore:                                                   --
    -- IrmsAD = sw_Itemp / 300% * 250% * 2 * sqrt(2)	,Q12        --
    --        = sqrt((Iu+Iw)^2-IuIw)*sqrt(2/3)/300*250*2*sqrt(2)    --
    --		  = sqrt((Iu+Iw)^2-IuIw)*63190/32768                    --
    --                                                              --
    --                       250                                    --
    -- 63190  = sqrt(2/3) * ----- * 2 * sqrt(2) * 32768             --
    --                       300                                    --
    --                                                              --
    ----------------------------------------------------------------*/

#if DINO
    swIAtemp = (SWORD)AN000 - (AD_uwIA0>>4);
    swICtemp = (SWORD)AN002 - (AD_uwIC0>>4);
// [ Add by DINO, 03/06/2009
	adc_swIAtemp = swIAtemp;
	adc_swICtemp = swICtemp;
// ]
    sw_Itemp = swIAtemp + swICtemp;	// dino, 03/29/2007
    ul_Itemp1 = (SLONG)sw_Itemp*sw_Itemp - (SLONG)swIAtemp*swICtemp ;	// Iu^2 + IuIw + Iw^2 = (Iu+Iw)^2 - IuIw
    sw_Itemp = uw_Sqrt32c(ul_Itemp1);
	IrmsAD1 = ((SLONG)sw_Itemp * 63190) >> 15;	// 3.34/sqrt(3) = 63190/32768	//2007/08/03	SCOTTY
    //---- finish Isum calculated(DINO) 03/29/2007------------------//
#else
    sw_Itemp   = AN000;
    sw_Itemp1  = AN002; 
    ul_Itemp2  = (ULONG)(sw_Itemp * sw_Itemp) + (ULONG)(sw_Itemp1 * sw_Itemp1);
    ul_Itemp1  = ul_Itemp2 + (SLONG)(sw_Itemp * sw_Itemp1);
    sw_Itemp   = uw_Sqrt32c(ul_Itemp1);
    IrmsAD1    = U16xU16divU16(sw_Itemp, 3332,1732);    
    //---- finish Isum calculated(SCOTTY) 03/01/2007----------------//
#endif

  
}

void ReadAD(void)
{
    SWORD swIbTemp;
    SLONG sltmp;
    
    //SWORD swIbTemp, swIAtemp, swICtemp;                   //clear Warning, Special.kung, 03/08/2023
    //ULONG ul_Itemp1, ul_Itemp2;                           //clear Warning, Special.kung, 03/08/2023
    //SWORD sw_Itemp, sw_Itemp1;                            //clear Warning, Special.kung, 03/08/2023



	// [ Change Output Direction, Added by sampo , 06/11/2009
	if (1){  // Delete CHGDIR Function, DINO, 08/03/2010
		AN000  = S12ADB0.ADDR0;	// Iu
		AN001  = S12ADB0.ADDR1;	// Iv
	}
	else{
		AN000  = S12ADB0.ADDR1;	// Iu
		AN001  = S12ADB0.ADDR0;	// Iv
	}
	// ]		
#if NEWIEDCB
    AN002  = S12ADB0.ADDR2;	// Iw
    AN003  = S12ADB0.ADDR3; // dcBus  
	AN100  = S12ADB1.ADDR0; // GFF_AD, DINO, 03/01/2010

	AN00  =  (UWORD)(AD0.ADDRA.WORD & 0x3FF);     // PGT, PG Type, IO Define, Sean, 06/25/2010       
	AN01  =  (UWORD)(AD0.ADDRB.WORD & 0x3FF);	    // SIN/COS, IO Define, Sean, 06/25/2010            
	AN101 =  S12ADB1.ADDR1;  // RESERVED, IO Define, Sean, 06/25/2010           
	AN02  =  (UWORD)(AD0.ADDRC.WORD & 0x3FF);     // TH2, IO Define, Sean, 06/25/2010                
	AN03  =  (UWORD)(AD0.ADDRD.WORD & 0x3FF);	    // TH1, IO Define, Sean, 06/25/2010                
	AN102 =  S12ADB1.ADDR2;    // AUI2, IO Define, Bernie, 07/22/2011              
	AN103 =  S12ADB1.ADDR3;    // AUI1, IO Define, Bernie, 07/22/2011  
	
	AN06  = (UWORD)(AD0.ADDRG.WORD & 0x3FF); // [Safty 1, Bernie, 2013/09/06]
    AN07  = (UWORD)(AD0.ADDRH.WORD & 0x3FF); // [Safty 2, Bernie, 2013/09/06]   
    AN08  = (UWORD)(AD0.ADDRI.WORD & 0x3FF); // [Safty 3, Bernie, 2013/09/06]           
    AN09  = (UWORD)(AD0.ADDRJ.WORD & 0x3FF); // [Safty 4, Bernie, 2013/09/06]   
#endif

    //------ Protection PHL and FanLock ( dino, 03/29/2007 )----------//

   //AN00 = ((ULONG)AN00*4095)>>10;
   AN01 = ((ULONG)AN01*4095)>>10;
   AN02 = ((ULONG)AN02*4095)>>10;
   AN03 = ((ULONG)AN03*4095)>>10;


   


    //S1*(-1/3)+2.5v, same as S2, S3
    sltmp = (SLONG)(AN000<<4) - (SLONG)AD_uwIA0;	// dino, 03/06/2007

    if (sltmp > 32767)
        AD_swIAPu = 32767;    
    else if (sltmp <-32767)
        AD_swIAPu = -32767;    
    else
        AD_swIAPu = sltmp;
        
    if ((pr[CTRLM]==DBCSECA)||(pr[AUTO_T]==10)){
        sltmp = (SLONG)(AN001<<4) - (SLONG)AD_uwIB0;	// dino, 03/06/2007

        if (sltmp > 32767)
            AD_swIBPu = 32767;    
        else if (sltmp <-32767)
            AD_swIBPu = -32767;    
        else
            AD_swIBPu = sltmp;

    }
    else{
        sltmp = (SLONG)(AN001<<4) - (SLONG)AD_uwIB0;	// dino, 03/06/2007

        if (sltmp > 32767)
            swIbTemp = 32767;    
        else if (sltmp <-32767)
            swIbTemp = -32767;    
        else
            swIbTemp = sltmp;
        
        AD_swIBPu = ((SLONG)swIbTemp * pr[CALI_REF])>>14;
        AD_swICPu = -(AD_swIAPu + AD_swIBPu);
    }

    AD_swIAPu = ((SLONG)AD_swIAPu + AD_swIAPu_Old) >> 1;
    AD_swIBPu = ((SLONG)AD_swIBPu + AD_swIBPu_Old) >> 1;
    AD_swICPu = ((SLONG)AD_swICPu + AD_swICPu_Old) >> 1;

    AD_swIAPu_Old = AD_swIAPu;
    AD_swIBPu_Old = AD_swIBPu;
    AD_swICPu_Old = AD_swICPu;

    //--------------------------------------------------------------//
    // Isum = sqrt(4/3(Iu^2+IuIw+Iw^2))				   				//
    // sqrt(4/3)*1.666 = 3.332/sqrt(3)				    			//
    //--------------------------------------------------------------//
// [ Move IrmsAD1 calculation to TimeBase_1ms(), Modify by DINO, 03/06/2009
    adc_swIAtemp = (SWORD)AN000 - (AD_uwIA0>>4);
    adc_swICtemp = (SWORD)AN002 - (AD_uwIC0>>4);
// ]


#if !SH7286	// Sean, 01/25/2010
    dcbusAD = AN4;	// dino, 03/06/2007
#else 
	dcbusAD = AN003;	// Modify, DINO, 03/01/2010
#endif    

#if SIBO_ENABLE //[Sibocom Function,Lyabryan,2020/6/15]
        //if ( EPS ){
        //    dcbusDC = pr[VEPS];			// DINO 02/18/2008
        //}
        //else{
    	    dcbusDC = ADC2Vdc(dcbusAD);	//SCOTTY 10/17/2007
        //}
#else
	    if ( EPS ){
            dcbusDC = pr[VEPS];			// DINO 02/18/2008
        }
        else{
    	    dcbusDC = ADC2Vdc(dcbusAD);	//SCOTTY 10/17/2007
        }
#endif
	
    
	//-- ACI value update --//
#if SH7286 //Sean, 01/25/2010
    AD_uwACIad = 0;	//Sean, 01/25/2010, temporarily
#else	
    AD_uwACIad = AN12;
#endif


	//-- AUI1 value update --//
	//if(pr[AUI1_COMMUN]==4096){   //[DLC, Bernie, 2014/10/06]
        AD_uwAUI1adReal = AN103;	// Bernie ,07/22/2011
    //}
    //else{
        //AD_uwAUI1adReal = pr[AUI1_COMMUN];
    //}

    if (abs(AD_uwAUI1adReal-AD_uwAUI1ad)<=1){
    	if (AD_AVIadChkCnt<=10){
    	    AD_AVIadChkCnt++;
    	}
    }
    else{
		AD_AVIadChkCnt = 0;
    }
	
    if (AD_AVIadChkCnt<10){
    	AD_uwAUI1ad = AD_uwAUI1adReal;
    }



	//-- AUI2 value update --//
	//if(pr[AUI2_COMMUN]==4096)    //[DLC, Bernie, 2014/10/06]
        AD_uwAUI2adReal = AN102;	//Bernie, 07/22/2011
    //else
       // AD_uwAUI2adReal = pr[AUI2_COMMUN];
    
    if (abs(AD_uwAUI2adReal-AD_uwAUI2ad)<=1){
    	if (AD_AUIadChkCnt<=10){
    	    AD_AUIadChkCnt++;
    	}
    }
    else{
		AD_AUIadChkCnt = 0;
    }

    if (AD_AUIadChkCnt<10){
    	AD_uwAUI2ad = AD_uwAUI2adReal;
    }

//========= SAFTY FUNCTION VOLTAGE =========//
    if(AN09 >= AD_3V)    
        S1_C = 1;
    else
        S1_C = 0;
    if(AN08 >= AD_3V)
        S2_C = 1;
    else
        S2_C = 0;
    if(AN07 >= AD_3V)
        S1_DC = 1;
    else
        S1_DC = 0;
    if(AN06 >= AD_3V)
        P_5V = 1;
    else
        P_5V = 0;
//=====================================//
}

#ifdef  _ADProg_C
    #undef  _ADProg_C
#endif

/************************************************************************
 Copyright (c) 2005 EMBU DELTA
 All rights reserved.
*************************************************************************
 End of this File (EOF):
 !!!!!!Do not put anything after this part!!!!!!!!!!!
*************************************************************************/
