#ifndef _INITIAL_VAR
	#define _INITIAL_VAR
#endif

#include "ProgHeader.h"



void  Initial_Var(void){
    UWORD i;

    /* ADProg======================================*/
    IrmsAD			        =0;
	IrmsAD1 		        =0;
	IrmsADOld		        =0;
	dcbusAD			        =0;
	dcbusADAVG		        =0;
	dcbusDCInit		        =0;
	AD_uwIA0		        =0;
	AD_uwIB0		        =0;
	AD_uwIC0		        =0;
	AD_uwPHL		        =0;
	AD_uwFLock		        =0;
	AD_uwAUI1ad		        =0;
	AD_uwAUI1adReal	        =0;
	AD_uwACIad		        =0;
	AD_uwAUI2ad		        =0;
	AD_uwAUI2adReal	        =0;
	AD_ulIA0		        =0;
	AD_ulIB0		        =0;
	AD_ulIC0		        =0;
    AD_swIAPu_Old           =0;
    AD_swIBPu_Old           =0;
    AD_swICPu_Old           =0;
    swIdssPu                =0;
    swIqssPu                =0;
    swIasRefPu              =0;
    swIbsRefPu              =0;
    swIcsRefPu              =0;
    adc_swIAtemp            =0;
    adc_swICtemp            =0;
    STO_status.ub           =0;
    /* A_MonitorPr======================================*/
    fkey.ul                 =0;     //Freq. Command
    fout.ul                 =0;     //Output Frequency
    PHLbusReLPF.sl          =0;     //Dcbus (Vdc)
    VcmdLLPF.sl             =0;     //Output Voltage (Vac)
    IrmsReLPF.sl            =0;     //Output Current (A rms)
    swMotorRpm              =0;     //Real Motor speed (RPM)
    pv                      =0;     //PID feedback (%)
    swTqRefPu               =0;     //Torque Command (%)
    PIDsource               =0;     //PID reference (%)
    APR_uwPGPosition        =0;     //PG1 position
    APR_uwZPosition         =0;     //PG1 Z-position
    APR_uwPG2PCom           =0;     //PG2 position
    PG2_ulSpdCmdLPF.ul      =0;     //PG2 velocity
    swAVICalib              =0;     //AVI percent (%)
    swACICalib              =0;     //ACI percent (%)
    swAUICalib              =0;     //AUI percent (%)
    mio_ulMfiNow            =0;     //DI value, Move from PH_MFIO_VLI_New.h, DINO, 09/01/2010
    mio_uwMfoNow            =0;     //Move from PH_MFIO_VLI_New.h, DINO, 09/01/2010
    mfi_now                 =0;     //Digital Input status
    mfo_now                 =0;     //Digital Output status
    SPR_swFFD               =0;
    CRM_slFlxFreqPu         =0;
    TB1_slSpdCmdPu          =0;
    SpDt_slSpdFdbPu         =0;
    Vcmd_LL                 =0;
    dcbusDC                 =0;
    AD_swIAPu               =0;
    AD_swIBPu               =0;
    AD_swICPu               =0;
    CUR_swIqseRefPu         =0;
    CUR_swIdseRefPu         =0;
    swCmdRpm                =0;
    swTqFbkPu               =0;
    uw_SCTEST               =0;
    uw_SCTEST2              =0;
    uw_SCTEST3              =0;
    uw_SCTEST4              =0;
    uw_SCTEST5              =0;
    uw_SCTEST6              =0;
    uw_SCTEST7              =0;
    uw_SCTEST8              =0;
    uw_fcomref              =0;
    uw_fcomfbk              =0;
    AN00                    =0;
    AN01                    =0;
    AN02                    =0;
    AN03                    =0;
    AN06                    =0;
    AN07                    =0;
    AN08                    =0;
    AN09                    =0;
    AN000                   =0;
    AN001                   =0;
    AN002                   =0;
    AN003                   =0;
    AN100                   =0;
    AN101                   =0;
    AN102                   =0;
    AN103                   =0;
    Pgc_uwCpo               =0;
    Pgc_uwCne               =0;
    Pgc_uwDpo               =0;
    Pgc_uwDne               =0;
    Pgc_uwApo               =0;
    Pgc_uwAne               =0;
    Pgc_uwBpo               =0;
    Pgc_uwBne               =0;
    Pgc_uwRpo               =0;
    Pgc_uwRne               =0;
    uw_PGtest               =0;
    uw_PGReCoDer            =0;
    DcbusDCLPF.sl           =0;
    /*BK_APR======================================*/
    APR_ubZChkCnt           =0;
    APR_ubTemp              =0;
    APR_ubMultiP            =0;
    APR_uwZarray[0]         =0;
    APR_uwZarray[1]         =0;
    APR_uwZarray[2]         =0;
    APR_uwZarray[3]         =0;
    APR_uwZarray[4]         =0;
    APR_uwZarray[5]         =0;
    APR_uwZarray[6]         =0;
    APR_uwZarray[7]         =0;
    APR_uwZarray[8]         =0;
    APR_uwTheta             =0;
    APR_uwThetaNoMx         =0;
    APR_uwThetaPu           =0;
    APR_uwP2PMem            =0;
    APR_uwZOServoP          =0;
    APR_ZeroTheta           =0;
    APR_ZeroThetaOld        =0;
    APR_uwPTarget           =0;
    APR_uwZpulseCnt         =0;
    APR_uwPCom              =0;
    APR_uwPG2PComOld        =0;
    APR_uwPFbk              =0;
    APR_uwThetaO            =0;
    APR_uwThetaO2           =0;
    APR_uwPGHome            =0;
    APR_uwDistance          =0;
    APR_uwOnPCNT            =0;
    APR_uwPGCycle           =0;
    ZCyclePeriod            =0;
    ZCycleCNT               =0;
    APR_slSpdCmd            =0;
    Psacc.ul                =0;
    Pacc.ul                 =0;
    PsaccMax.ul             =0;
    VcomFmax.ul             =0;
    APR_slZPLPF.sl          =0;
    /*BK_ATuning======================================*/
    DBC_period              =0;
    DBC_uwDuty_t_10K        =0;
    DBC_uwD_u_10KUcom       =0;
    uwCurCalibRatio         =0;
    DBC_slCMPUaInt          =0;
    DBC_slDuty_10KI1        =0;
    DBC_slDuty_10KI2        =0;
    DBC_slDuty_5KI1         =0;
    DBC_slDuty_5KI2         =0;
    DBC_slUdc_10KI1         =0;
    DBC_slUdc_10KI2         =0;
    DBC_slUdc_5KI1          =0;
    DBC_slUdc_5KI2          =0;
    CCB_slIaSum             =0;
    CCB_slIbSum             =0;
    TUN_Sector              =0;
    TUN_TESTCNT             =0;
    TUN_Method              =0;
    TUN_TuningCNT           =0;
    TUN_IntegralCnt         =0;
    TUN_CatchPoint          =0;
    TUN_uwTB1CNT            =0;
    TUN_uwUd_K              =0;
    TUN_uwLSCNT             =0;
    TUN_uwLSCNT1            =0;
    TUN_STEPANGMAX          =0;
    TUN_STEPANG             =0;
    TUN_Z_COMFIRM           =0;
    TUN_Z_CAPTURECNT        =0;
    TUN_Z_CAPTURECNTZ       =0;
    TUN_Z_COUNT             =0;
    PG_Zoffset              =0;
    TUN_SINDATAMAX          =0;
    TUN_COSDATAMAX          =0;
    TUN_SINDATAMIN          =0;
    TUN_COSDATAMIN          =0;
    SpDt_uwAnglePeriod      =0;
    SpDt_uwPG1CNT_Org1      =0;
    TUN_TunLSCNT            =0;
    TUN_uwLSTmax            =0;
    TUN_uwLSTmin            =0;
    TUN_uwLSTIME            =0;
    TUN_uwVdout             =0;
    TUN_uwUVWsector         =0;
    TUN_uwImNRatioPu        =0;
    TUN_uwQfRatioPu         =0;
    TUN_uwEmNPu             =0;
    TUN_uwImNPu             =0;
    TUN_uwIdCurr            =0;
    TUN_uwInitTheta         =0;
    TUN_uwPMTunCnt          =0;
    PG_Zoffset_1387         =0;
    TUN_swIdseRefPu         =0;
    TUN_swIdseFdbPu         =0;
    TUN_swUoutPu            =0;
    TUN_swUaPu              =0;
    TUN_swUbPu              =0;
    TUN_swUalfa             =0;
    TUN_swUbeta             =0;
    TUN_UalfaZ1             =0;
    TUN_UbetaZ1             =0;
    TUN_VoltInP             =0;
    TUN_VoltInQ             =0;
    TUN_swUqssPuZ1          =0;
    TUN_swZANGLE            =0;
    TUN_swIhigh             =0;
    TUN_swImid              =0;
    TUN_swIlow              =0;
    TUN_slUdIntPu           =0;
    TUN_slIphS1             =0;
    TUN_slUphS1             =0;
    TUN_slIphS2             =0;
    TUN_slUphS2             =0;
    TUN_slFreqPu            =0;
    TUN_slIsqr              =0;
    TUN_slUsqr              =0;
    TUN_slP                 =0;
    TUN_slQ                 =0;
    TUN_slP1                =0;
    TUN_slQ1                =0;
    TUN_slP2                =0;
    TUN_slQ2                =0;
    TUN_slPQSquare          =0;
    TUN_slXpu               =0;
    TUN_slLFSLFminPu        =0;
    TUN_slFcmdPuMax         =0;
    TUN_slIqIntePu          =0;
    TUN_HFSS_P_I1F1         =0;
    TUN_HFSS_P_I1F2         =0;
    TUN_HFSS_P_I2F1         =0;
    TUN_HFSS_P_I2F2         =0;
    TUN_HFSS_I_I1F1         =0;
    TUN_HFSS_I_I1F2         =0;
    TUN_HFSS_I_I2F1         =0;
    TUN_HFSS_I_I2F2         =0;
    TUN_slI0sqr             =0;
    TUN_slI0Sqr6            =0;
    TUN_slI0Sqr5            =0;
    TUN_slI0Sqr4            =0;
    TUN_slI0Sqr3            =0;
    TUN_slI0Sqr2            =0;
    TUN_slI0Sqr1            =0;
    TUN_slX6                =0;
    TUN_slX5                =0;
    TUN_slX4                =0;
    slXsNPu                 =0;
    slEsNPu                 =0;
    TUN_uwRsPu              =0;
    TUN_HFSS_R_F1           =0;
    TUN_HFSS_R_F2           =0;
    TUN_HFSS_R_F0           =0;
    TUN_uwRrPu              =0;
    TUN_uwL1sigmaPu         =0;
    TUN_uwLm1Pu             =0;
    TUN_uwLmPu              =0;
    TUN_uwI0Pu              =0;
    TUN_uwLmx6Pu            =0;
    TUN_uwLmx5Pu            =0;
    TUN_uwLmx4Pu            =0;
    TUN_uwLmxPu             =0;
    TUN_uwLmx2Pu            =0;
    TUN_uwLmx1Pu            =0;
    mrs_LpfKit              =0;
    TUN_uwTheta             =0;
    TUN_uwSinIndex          =0;
    TUN_uwCosIndex          =0;
    uwXPu                   =0;
    uwRPu                   =0;
    uwIsPu                  =0;
    uwX1Pu                  =0;
    uwIs1Pu                 =0;
    uwX2Pu                  =0;
    uwIs2Pu                 =0;
    uwTrPu                  =0;
    swEalfaPu               =0;
    swEbetaPu               =0;
    swIalfaOldPu            =0;
    swIbetaOldPu            =0;
    slUalfaPuLPF            =0;
    slUbetaPuLPF            =0;
    slIalfaPuLPF            =0;
    slIbetaPuLPF            =0;
    slQRefPu                =0;
    slQFdbPu                =0;
    /*BK_CurrentMod======================================*/
    CRM_uwTheta             =0;
    CRM_uwaxisCOR           =0;
    CRM_SinSection          =0;
    CRM_uwSinIndex          =0;
    CRM_uwCosIndex          =0;
    SinValue                =0;
    CosValue                =0;
    CRM_swThetaStep         =0;
    CRM_swIqPu              =0;
    CRM_swIdPu              =0;
    CRM_ulThetaR            =0;
    CRM_ulThetaSL           =0;
    CRM_slSpdPu             =0;
    CRM_slWslPu             =0;
    CRM_ImPuLPF.sl          =0;
    /*BK_DeadtimeComp======================================*/ 
    DBC_swAtemp             =0;
    DBC_swBtemp             =0;
    DBC_swCtemp             =0;
    UaDBC                   =0,
    UbDBC                   =0;
    DBC_swSTEPANGLE         =0;
    UcDBC                   =0;
    DBC_uwIbCnt             =0;
    DBC_uwIcCnt             =0;
    DBC_ATmCNT              =0;
    DBC_BTmCNT              =0;
    DBC_CTmCNT              =0;
    DBC_ATm                 =0;
    DBC_BTm                 =0;
    DBC_CTm                 =0;
    DBCDt                   =0;
    DBCDu                   =0;
    DBheight                =0;
    CLorOP                  =0;
    /*BK_EstJ======================================*/ 
    EsJ_ubKInt              =0;
    EsJ_ubsteady            =0;
    EsJ_uwKJGain            =0;
    EsJ_uwLPG               =0;
    EsJ_uwJmPu              =0;
    EsJ_swJPu_New           =0;
    EsJ_swTePu              =0;
    EsJ_slJPu               =0;
    EsJ_slTeInt             =0;
    EsJ_slTLPu_FWD          =0;
    EsJ_slTLPu_REV          =0;
    EsJ_slSpdtmpPu          =0;
    /*BK_FFD======================================*/ 
    FFD_swIqsePu            =0;
    FFD_swIdsePu            =0;
    FFD_swImPu              =0;
    FFD_swUqseOutPu         =0;
    FFD_swUdseOutPu         =0;
    FFD_slFlxFreqPu         =0;
    /*BK_FluxControl======================================*/ 
    FLX_uwWslMaxPu          =0;
    FLX_swIdseRefPu         =0;
    FLX_swFlxFreqPu         =0;
    FLX_swVsMaxPu           =0;
    FLX_swVoutPu            =0;
    FLX_slWslErrKi          =0;
    FLX_slVsErrKi           =0;
    FLX_IdRefPuLPF.sl       =0;
    /*BK_PG2Ref======================================*/ 
    PG2_1msCNT              =0;
    PG2R_uwCmdLPG           =0;
    PG2_uwCNTNew            =0;
    PG2_uwCNTOld            =0;
    PG2_uwCNTOrg            =0;
    PG2_uwTheta             =0;
    PG2_swCNTIntgral        =0;
    PG2_ulNpulse            =0;
    PG2_slAPRIntgral        =0;
    PG2_slSpdCmd            =0;
    /*BK_PWMGen======================================*/ 
    Duty_swTasInPu          =0;
    Duty_swTbsInPu          =0;
    Duty_swTcsInPu          =0;
    PWM_swTaInPu            =0;
    PWM_swTbInPu            =0;
    PWM_swTcInPu            =0;
    PWM_swTaOut             =0;
    PWM_swTbOut             =0;
    PWM_swTcOut             =0;
    experiod_Buf            =0;
    PWM_swTaOut_Buf         =0;
    PWM_swTbOut_Buf         =0;
    PWM_swTcOut_Buf         =0;
    update_experiod         =0;
    experiod_Buf            =0;
    PWM_swGBP               =0;
    PWM_swTabOut            =0;
    PWM_swTbcOut            =0;
    PWM_swTcaOut            =0;
    swTest1                 =0;
    swTest2                 =0;
    swTest3                 =0;
    swTest4                 =0;
    ulKu4Uout               =0;
    PWM_Status.ub           =0;
    EPS_Direct_flag.ub      =0;
    uw_UPdeadtime           =0;
    uw_LOWdeadtime          =0;
    /*BK_RegCurrent======================================*/ 
    CUR_uwqKpPu             =0;
    CUR_uwqKiPu             =0;
    CUR_uwdKpPu             =0;
    CUR_uwdKiPu             =0;
    CUR_swIqseRefPuOld      =0;
    CUR_swIqseFdbPu         =0;
    CUR_swIdseFdbPu         =0;
    CUR_swUqseOutPu         =0;
    CUR_swUdseOutPu         =0;
    CUR_slIqInteg           =0;
    CUR_slIdInteg           =0;
    CUR_slWindUp            =0;
    /*BK_RegSpeed======================================*/ 
    SPR_ubASRCnt            =0;
    SPR_ubT1UnderCntOLD     =0;
    SPR_ubT1OverCntOLD      =0;
    SPR_uwKpPu              =0;
    SPR_uwKpKiPu            =0;
    SPR_uwKrPu              =0;
    SPR_uwTqLPG             =0;
    SPR_uwKpKiGain          =0;
    SPR_uw_posCtime         =0;
    SPR_uwKrGain            =0;
    SPR_uwPPILPG            =0;
    SPR_swIqseRefPu         =0;
    SPR_swIqseRefLimPu      =0;
    SPR_swTqRefPu           =0;
    sw_fcomerr              =0;
    swTqInPu                =0;
    SPR_swIqseFWDMPu        =0;
    SPR_swIqseFWDRPu        =0;
    SPR_swIqseREVMPu        =0;
    SPR_swIqseREVRPu        =0;
    SPR_swPIVUVCnt          =0;
    SPR_swTqOfstPu          =0;     // Iqe Compensation of New PPI Control
    SPR_slSpdRefPu          =0;
    SPR_slSpdFdbPu          =0;
    SPR_slSpdInteg          =0;
    SPR_slIqseRefPu_LP      =0;
    SPR_slSpdRefPu_Old      =0;
    SPR_slspdFFDPu          =0;
    SPR_slspePIFout         =0;
    SPR_slTqRefLimPu        =0;
    SPR_sltest              =0;
    SPR_slIqseTurqRefPu     =0;
    SPR_slSpdSatPu          =0;
    SPR_slIqseLimit         =0;
    SPR_slPIVthidaCom       =0;     //PPI Control Position Command
    SPR_slPIVthidaFbk       =0;     //PPI COntrol Position Feedback
    SPR_slPIVThidaErr       =0;
    SPR_slPIVInteg          =0;
    SPR_ulThetaRef          =0;
    SPR_ulPIVKp             =0;
    SPR_ulThetaFdb          =0;
    SPR_ulSpdRefPuLPF2      =0;     // LPF of SPR_slSpdRefPu of Low WORD
    SPD_slPOScon.sl         =0;     
    SPR_IqseRefPuLPF.sl     =0;
    SPR_SpdRefPuLPF.sl      =0;     // LPF of SPR_slSpdRefPu of High WORD
    SPR_TqOfstPu.sl         =0;     // Iqe Compensation of New PPI Control
    SPR_swSCTEST0           =0;
    SPR_swSCTEST1           =0;
    SPR_swSCTEST2           =0;
    TB1_swPGQualityDsp      =0;
    SPR_swPGoverflwCnt      =0;
    SPR_swPGoverflwCnt_old  =0;
    SPR_ulPGQualityCnt      =0;
    SPR_uwPGTCNT            =0;
    SPR_uwPGTCNT_old        =0;
    SPR_uwPGDIR             =0;
    SPR_uwPGDIRCnt          =0;
    SPR_uwPGDIRRec          =0;
    TB1_uwPGQuality_1sec    =0;
    TB1_uwPGQualityZcnt     =0;
    swTqInPu_Mon            =0;  //[Pre-Torque with Load-Cell,Lyabryan,2019/01/08]
    /*BK_SpDtPG1======================================*/ 
    SpDt_ubT0OverCnt        =0;
    SpDt_ubT0OvCnt_New      =0;
    SpDt_ubT0OvCnt_Old      =0;
    SpDt_ubPG1PoNePusCnt    =0;     // have Positive & Negative pulse
    SpDt_ubT1OverCnt        =0;
    SpDt_ubT1UderCnt        =0;
    SpDt_ub100usCnt         =0;
    SpDt_uwPG1CNT_New       =0;
    SpDt_uwPG1CNT_Old       =0;
    SpDt_uwPG1Wdh_New       =0;
    SpDt_uwPG1Wdh_Old       =0;
    SpDt_uwPG1LoSpdCNT_Old  =0;
    SpDt_uwPG1LoSpdCNT_Z1   =0;
    SpDt_uwPG1CNT           =0;
    SpDt_uwPG1CNT_Org       =0;
    SpDt_uwPG1CNT_OrgNoMx   =0;
    SpDt_uwChanLeRe         =0;
    SpDt_uwHiLPG            =0;
    SpDt_uwLoLPG            =0;
    SpDt_uwPGErrDet         =0;
    SpDt_uwOvSpdDet         =0;
    SpDt_uwSpdDeDet         =0;
    SpDt_uwPGF1ErrCnt       =0;
    SpDt_uwPGLossCnt        =0;
    SpDt_uwPGLossCnt1       =0;
    SpDt_uwPGLossCnt2       =0;
    SpDt_uwPGLossCnt3       =0;     // PG Loss Hardware Detected counter
    SpDt_uwPGLossCnt4       =0;     // Absolute PG Loss Detected counter
    SpDt_uwOvSpdCnt         =0;
    SpDt_uwSpdDeCnt         =0;
    SpDt_uwPG1100usCNT_Old  =0;
    SpDt_uwPGcorrectvalue   =0;
    SpDt_uwFfbk             =0;
    SpDt_uwPGCDin_old       =0;
    SpDt_uwPGABin_old       =0;
    SpDt_uwNoground_CNT     =0;
    SpDt_uwAccCalcul        =0;
    SpDt_uwAccOpt           =0;
    SpDt_uwAccCalculOld     =0;
    TB3_swAccOpt            =0;     //[Rationa 362631, Special.Kung]
    TB3_uwSampleRate        =0;     //[Rationa 362631, Special.Kung]
    TB3_slAccCalculOld      =0;     //[Rationa 362631, Special.Kung]
    OverAccTimeSet          =0;
    uwOverAccLev            =0;
    uwOverAccCnt            =0;
    AccTemp_LPF.sl          =0;
    SpDt_slPG1FdbPu_temp    =0;
    SpDt_slPG1FdbPu_temp1   =0;
    SpDt_swPG1LoSpdCNT_Err  =0;
    SpDt_swPG1CNT_ErrOld    =0;
    SpDt_swPGecycle         =0;
    SpDt_sw500usCNT_Err     =0;
    SpDt_sw40ms_tmp         =0;
    SpDt_sw200ms_Flag       =0;
    SpDt_swPGCDerr_Detect   =0;
    SpDt_swNoground_CNT     =0;
    SpDt_swCDerrold         =0;
    SpDt_ulPG1Npulse        =0;
    SpDt_ulPG1NpulseNoMx    =0;
    SpDt_ulPG1Kmt_HiPus     =0;
    SpDt_ulPG1Kmt_HiPus1    =0;
    SpDt_ulPG1Kmt_LoPus     =0;
    SpDt_ulKTheta           =0;
    SpDt_ulThetaR           =0;
    SpDt_ulPG1Kmt_100us     =0;
    SpDt_slPG1FdbPu         =0;
    SpDt_slOvSpdLePu        =0;
    SpDt_slSpdDeLePu        =0;
    SpDt_uwPGErrTmp         =0;
    SpDt_uwPG1CNT_Save      =0;
    PGABerr_add.sl          =0;
    PGABerr_add_old.sl      =0;
    PGCDerr_add.sl          =0;
    PGCDerr_add_old.sl      =0;
    PGABerr_LPF.sl          =0;
    PGCDerr_LPF.sl          =0;
    /*BK_Tabc2dq======================================*/ 
    T32_swIasInPu           =0;
    T32_swIbsInPu           =0;
    T32_swIdssOutPu         =0;
    T32_swIqssOutPu         =0;
    /*BK_TestSource======================================*/
    TS_swSoOutPu            =0;
    TS_swAmpPu              =0;
    TS_swAmpLimPu           =0;
    TS_swOffsetPu           =0;
    TS_uwcnt                =0;
    TS_uwTheta              =0;
    TS_slSoFreqPu           =0;
    TS_ulKTheta             =0;
    /*BK_TqCmd======================================*/
    TqC_uwTqCmdPu           =0;
    Tqc_uwTqCmdLPG          =0;
    TqC_uwPSpdLimRe         =0;
    TqC_uwNSpdLimRe         =0;
    TqC_swTqCmd             =0;
    TqC_swTqSetPu           =0;
    TqC_swIqseRefPu         =0;
    TqC_swTqOfstPu          =0;
    TqC_swPSpdLimPu         =0;
    TqC_swNSpdLimPu         =0;
    TqC_slTqCmdPuLPF        =0;
    TqC_slTqOfstPu.sl       =0; //[Pre-Torque with Load-Cell,Lyabryan,2019/01/08]
    /*BK_TStat2Syn======================================*/
    TsE_swIqssInPu          =0;
    TsE_swIdssInPu          =0;
    TsE_swIqseOutPu         =0;
    TsE_swIdseOutPu         =0;
    /*BK_TSyn2Stat======================================*/
    TeS_swUqseInPu          =0;
    TeS_swUdseInPu          =0;
    TeS_swUqssOutPu         =0;
    TeS_swUdssOutPu         =0;
    /*CM_FOC======================================*/
    uwK1Pu                  =0;
    /*CM_FOCPG======================================*/

    /*CM_FOCPM======================================*/

    /*CM_TQCPG======================================*/

    /*CM_VF======================================*/
    Ismax_uwPu              =0;
    Is_uwPu                 =0;
    VF_Vcmd                 =0;
    VF_uwVcmpMax            =0;
    fs_nonlinear            =0;
    Tr                      =0;
    VFTB1_swUoutPu          =0;
    VF_swUout               =0;
    VF_swSlip               =0;
    Is                      =0;
    I2                      =0;
    PowerInRe               =0;
    I1                      =0;
    I5                      =0;
    I6                      =0;
    PG_integral             =0;
    Pin                     =0;
    PowerIn                 =0;
    slPowerInLPF            =0;
    QowerIn                 =0;
    Power_S                 =0;
    Culoss                  =0;
    Coreloss                =0;
    PowerGap                =0;
    VF_VcompPuLPF.sl        =0;
    VF_SlipLPF.sl           =0;
    VF_SlipLPF_out.sl       =0;
    VF_slIqeLPF.sl          =0;
    VF_slIdeLPF.sl          =0;
    SlinI                   =0;
    SlinF                   =0;
    Inl_integral.sl         =0;
    adjcnt                  =0;
    tq_boost                =0;
    nl_boost                =0;
    HFI_swUoutPu            =0;
    HFI_swIqseOutPu         =0;
    AD_swIAPu_Diff          =0;
    AD_swIBPu_Diff          =0;
    AD_swICPu_Diff          =0;
    TB2Cnt                  =0;
    IAPCnt                  =0;
    IANCnt                  =0;
    IBPCnt                  =0;
    IBNCnt                  =0;
    ICPCnt                  =0;
    ICNCnt                  =0;
    PhaseCnt                =0;
    uwTGain                 =0;
    Start_Section           =0;
    Start_Section_old       =0;
    TUN_uwSection           =0;
    Zpulse                  =0;
    uwPGInit                =0;
    AD_uwIAPu_MaxSum        =0;
    AD_uwIBPu_MaxSum        =0;
    AD_uwICPu_MaxSum        =0;
    AD_uwIAPu_MinSum        =0;
    AD_uwIBPu_MinSum        =0;
    AD_uwICPu_MinSum        =0;
    PM_swTmax               =0;
    PM_swTmin               =0;
    /*COEFhandel======================================*/
    COF_ubMPolePair         =0;
    COF_PolePair            =0;
    COF_Poles               =0;
    AD_AUIadChkCnt          =0;
    AD_AVIadChkCnt          =0;
    COF_uwVbRe              =0;
    COF_uwFbRe              =0;
    COF_ulIbRe              =0; // Jerry.sk.tseng for GFC High elecator 2021/08/17
    COF_uwRbRe              =0;
    COF_uwLbRe              =0;
    COF_uwTbRe              =0;
    COF_uwJbRe              =0;
    COF_uwPbRe              =0;
    COF_uwVratePu           =0;
    COF_uwMIratePu          =0;
    COF_uwIIratePu          =0;
    COF_uwI0Pu              =0;
    COF_uwFslipRate         =0;
    COF_uwFRatePu           =0;
    COF_uwFslipMAX          =0;
    COF_uwCTIratePu         =0;
    COF_uwVTIratePu         =0;
    COF_uwTqrateRe          =0;
    COF_uwTqratePu          =0;
    COF_uwTqMaxPu           =0;
    COF_uwSSIratedPu        =0;
    COF_uwImotorNP          =0;
    COF_uwSPDPMFFD          =0;
    COF_uwIdsLPG            =0;
    COF_uwVEPSPu            =0;
    COF_uwFepsLimit         =0;     //EPS limit freq.
    COF_uwTqSlopePu         =0;     //Torque decrease slope
    COF_uwRrPu              =0;
    COF_uwRsPu              =0;
    COF_uwLxPu              =0;
    COF_uwLmPu              =0;
    COF_Tr_inv              =0;
    COF_uwKt                =0;
    Rs                      =0;
    COF_uwZoffset           =0;
    COF_ulKTheta            =0;
    COF_ulFslipRatePu       =0;
    COF_ulFslipMAXPu        =0;
    COF_uwMIrRe             =0;
    COF_uwMPRe              =0;
    COF_uwRPMRe             =0;
    COF_uwPole              =0;
    COF_uwMI0Re             =0;
    COF_uwMRsRe             =0;
    COF_uwMLmRe             =0;
    COF_uwMFrRe             =0;     // Motor Rated Freq. calculated by Motor RPM
    COF_uwVUPSRe            =0;
    COF_uwSlipRe            =0;
    COF_uwIm1Pu             =0;
    COF_uwRs1Pu             =0;
    COF_uwRr1Pu             =0;
    COF_uwLm1Pu             =0;
    COF_uwLx1Pu             =0;
    COF_uwIm2Pu             =0;
    COF_uwRs2Pu             =0;
    COF_uwRr2Pu             =0;
    COF_uwLm2Pu             =0;
    COF_uwLx2Pu             =0;
    COF_uwIm3Pu             =0;
    COF_uwRs3Pu             =0;
    COF_uwRr3Pu             =0;
    COF_uwLm3Pu             =0;
    COF_uwLx3Pu             =0;
    COF_uwTctrTb2Pu         =0;
    COF_uwKUdcPuCnv         =0;
    COF_uwPassWord          =0;
    uwtest1                 =0;
    uwtest2                 =0;
    uwtest3                 =0;
    uwtest4                 =0;
    uwtest5                 =0;
    uwtest6                 =0;
    uwtest7                 =0;
    uwtest8                 =0;
    uwtest9                 =0;
    uwtest10                =0;
    uwtest11                =0;
    uwtest12                =0;
    uwtest13                =0;
    uwtest14                =0;
    uwtest15                =0;
    uwtest16                =0;
    uwtest17                =0;
    uwtest18                =0;
    uwtest19                =0;
    uwtest20                =0;
    uwtest21                =0;
    uwtest22                =0;
    uwtest23                =0;
    uwtest24                =0;
    uwtest25                =0;
    COF_uwVBase1_4          =0;
    COF_uwVBase1_8          =0;
    COF_uwFBase1_4          =0;
    COF_uwFBase3_10         =0;
    COF_uwI0DtLPu           =0;
    COF_uwBemfPu            =0;     // Motor BEMF, phase to phase, rms
    COF_sltest1             =0;
    /*DLC======================================*/
    DLC_ulDacc              =0;
    DLC_ulD2                =0;
    DLC_ulDcon              =0;
    DLC_ulD3                =0;
    DLC_ulDdec              =0;
    DLC_ulD4                =0;
    DLC_ulDStop             =0;
    for(i=0;i<0x4B;i++){
        DLC_ulPgLev[i]=0;     //unit - pg pulse
    }
    DLC_ulPgBrd             =0;
    DLC_ulPgSen             =0;     //LD, LU PG脈衝數
    DLC_ulPgCnt             =0;
    DLC_ulPgUp              =0;
    DLC_ulPgDn              =0;
    DLC_ulPgDD1             =0;
    DLC_ulPgDD2             =0;
    DLC_ulPgDD3             =0;
    DLC_ulPgDD4             =0;
    DLC_ulPgUD1             =0;
    DLC_ulPgUD2             =0;
    DLC_ulPgUD3             =0;
    DLC_ulPgUD4             =0; 
    DLC_ulPgUL              =0;
    for(i=0;i<=DLCFLOORMAX;i++){
        DLC_ulPosLev[i]=0;     //unit - 0.1mm
    }
    DLC_ulPosVal            =0;
    DLC_ulPosPar.ul            =0;     // DLC position offset
    DLC_ulOffset            =0;     // DLC position offset
    DLC_ulPosDD1            =0;
    DLC_ulPosDD2            =0;
    DLC_ulPosDD3            =0;
    DLC_ulPosDD4            =0;
    DLC_ulPosUD1            =0;
    DLC_ulPosUD2            =0;
    DLC_ulPosUD3            =0;
    DLC_ulPosUD4            =0;
    DLC_ulPosUL             =0;     
    COF_ulPls2MMgain        =0;
    DLC_ulCurSpd            =0;
    DLC_ulCurSpdOld         =0;     //[GFC  DLC speed cruve,Special.Kung]
    DLC_uwNorTmr            =0;     //[GFC  DLC speed cruve,Special.Kung]
    DLC_ulAcc               =0;     //[GFC  DLC speed cruve,Special.Kung]
    PR_S4ACC1               =0;
    PR_S4ACC2               =0;
    PR_S4DEC1               =0;
    PR_S4DEC2               =0;
    DLC_uwPOWCnt            =0;
    DLC_uwInit              =0;
    DLC_uwTR1               =0;
    DLC_uwTR2               =0;
    DLC_uwTR3               =0;
    DLC_uwTR4               =0;
    DLC_uwT1                =0;     //運算後, S1的時間
    DLC_uwT2                =0;     //運算後, S2的時間
    DLC_uwT3                =0;     //運算後, S3的時間
    DLC_uwT4                =0;     //運算後, S4的時間
    DLC_uwTd                =0;     //運算後, eq dec的時間
    DLC_uwTc                =0;     //等速段時間
    DLC_uwRateSpd           =0;
    DLC_uwTRa               =0;     //idea Tacc
    DLC_uwTRd               =0;     //idea Tdec
    DLC_uwTd                =0;
    DLC_uwAa                =0;     //idea Aacc
    DLC_uwAd                =0;     //idea Adec
    DLC_uwJR1               =0;     //idea Jerk1
    DLC_uwJR2               =0;     //idea Jerk2
    DLC_uwJR3               =0;     //idea Jerk3
    DLC_uwJR4               =0;     //idea Jerk4
    DLC_uwJ4                =0;
    DLC_uwVR1               =0;     //idea spd variable V1
    DLC_uwVR2               =0;     //idea spd variable V2
    DLC_uwVR3               =0;     //idea spd variable V3
    DLC_uwVR4               =0;     //idea spd variable V4
    DLC_uwV1                =0;     //real spd variable V1
    DLC_uwV2                =0;     //real spd variable V2
    DLC_uwV3                =0;     //real spd variable V3
    DLC_uwV4                =0;     //real spd variable V4
    DLC_uwVc                =0;     //real const spd
    DLC_uwVd                =0;     //real spd variable Vdec
    DLC_uwV4Dif             =0;
    DLC_uwS1Tmr             =0;
    DLC_uwAccTmr            =0;
    DLC_uwS2Tmr             =0;
    DLC_uwConTmr            =0;
    DLC_uwS3Tmr             =0;
    DLC_uwDecTmr            =0;
    DLC_uwS4Tmr             =0;
    DLC_uwInsAccTmr         =0;
    DLC_uwInsDecTmr         =0;
    MTU1_Old                =0;
    DLC_uwWelTra            =0;
    DLC_uwTra1              =0;
    DLC_uwTra2              =0;
    DLC_uwTra3              =0;
    DLC_uwTra4              =0;
    DLC_uwTra5              =0;
    DLC_uwSpdTra            =0;
    DLC_uwEeprom            =0;
    DLC_uwTra3              =0;
    DLC_uwTra4              =0;
    DLC_uwJD                =0;
    DLC_uwTD                =0;
    DLC_uwTDCnt             =0;
    DLC_uwATmp              =0;
    DLC_uwFlagCnt           =0;
    //DLC_uwS4Cnt             =0;	// Mitong 20220513 del
    DLC_uwPeriodCnt         =0;
    DLC_uwDCICnt            =0;
    DLC_uwSfbk              =0;
    DLC_ubSubtra            =0;     //Subtra addr, H=tra, L=Subtra
    DLC_ubtra               =0;
    DLC_ubLevMax            =0;
    DLC_ubLevMin            =0;
    DLC_ubLevCur            =0;     //Cur addr, H=Tar, L=Cur
    DLC_ubLevTar            =0;
    DLC_ubLevOk             =0;
    DLC_ubMode              =0;     //Mode addr, H=ModeOld, L=Mode
    DLC_ubModeOld           =0;
    DLC_ubWelTuntra         =0;     //map WelTuntra addr, H=PgPosClr, L=WelTuntra
    DLC_ubDIR               =0;
    DLC_ubCnt               =0;
    DLC_ubDecel             =0;
    DLC_uwAutoTar           =0;
    DLC_uwEM.uw             =0;    
	DLC_ubSpdLimFlag		=0;//Artemis speed limit, James, 20200220
    /*IODLC======================================*/
    IODLC_ubArea_status     =0;
    IODLC_uwPR_J1           =0;
    IODLC_uwPR_J2           =0;
    IODLC_uwPR_J3           =0;
    IODLC_uwPR_J4           =0;
    IODLC_uwPR_Ts1          =0;
    IODLC_uwPR_Tacc         =0;
    IODLC_uwPR_Ts2          =0;
    IODLC_uwPR_Ts3          =0;
    IODLC_uwPR_Tdec         =0;
    IODLC_uwPR_Ts4          =0;
    IODLC_uwPR_Tl           =0;
    IODLC_uwPR_Tfa          =0;
    IODLC_uwPR_Tfd          =0;
    IODLC_uwPR_Th           =0;
    IODLC_uwPR_Th_Det       =0;
    IODLC_uwPR_Th_CNT       =0;
    IODLC_uwPR_Tl_Det       =0;
    IODLC_uwPR_Tl_CNT       =0;
    IODLC_uwPR_delta_fs2    =0;
    IODLC_uwPR_delta_fs3    =0;
    IODLC_uwPR_delta_fs4    =0;
    IODLC_uwPR_fs4          =0;
    IODLC_uwPR_fl           =0;
    IODLC_uwPR_fMAX         =0;
    IODLC_uwPR_Adec         =0;
    IODLC_ulPR_Distance     =0;
    IODLC_uwArea_J1         =0;
    IODLC_uwArea_J2         =0;
    IODLC_uwArea_J3         =0;
    IODLC_uwArea_J4         =0;
    IODLC_uwArea_Ts1        =0;
    IODLC_uwArea_Tacc       =0;
    IODLC_uwArea_Ts2        =0;
    IODLC_uwArea_Ts3        =0;
    IODLC_uwArea_Tdec       =0;
    IODLC_uwArea_Ts4        =0;
    IODLC_uwArea_Tl         =0;
    IODLC_uwArea_Tfa        =0;
    IODLC_uwArea_Tfd        =0;
    IODLC_uwArea_Th         =0;
    IODLC_uwArea_delta_fs2  =0;
    IODLC_uwArea_delta_fs3  =0;
    IODLC_uwArea_delta_fs4  =0;
    IODLC_uwArea_fs4        =0;
    IODLC_uwArea_fl         =0;
    IODLC_uwArea_fMAX       =0;
    IODLC_uwArea_Adec       =0;
    IODLC_uwArea_Tdec_now   =0;
    IODLC_uwPRDtotal        =0;
    IODLC_uwSpeed           =0;
    IODLC_uwdecMaxSpeed     =0;
    uwspeed_max             =0;
    uwspeed_tmp             =0;
    IODLC_swArea_Th_Det     =0;
    ulcul_tmp               =0;
    ulcul_tmp1              =0;
    IODLC_ulPRDtotal        =0;
    IODLC_ulDtotal_dp       =0;
    IODLC_ulPR_Ts2x3        =0;
    IODLC_ulPR_Ts3x3        =0;
    IODLC_ulPR_Ts4x3        =0;
    IODLC_ulArea_Ts2x3      =0;
    IODLC_ulArea_Ts3x3      =0;
    IODLC_ulArea_Ts4x3      =0;
    IODLC_ulDs2             =0;
    IODLC_ulDh              =0;
    IODLC_ulDs3             =0;
    IODLC_ulDdec            =0;
    IODLC_ulDs4plusDl       =0;
    IODLC_ulDtotal          =0;
    IODLC_ulSFDistance      =0;
    IODLC_ulCPSDistance     =0;
    CRPLS_uwJlim            =0;
    CRPLS_ulTs4             =0;
    CRPLS_ulJs4             =0;
    cul_speed_tmp           =0;
    cul_D_tmp               =0;
    IODLC_sleqb             =0;
    IODLC_sleqc             =0;
    IODLC_sleqFm            =0;
    IODLC_sleqFlim          =0;
    IODLC_sldelta_sdec      =0;
    IODLC_control_flag.uw   =0;
    IODLC_CRPLS_flag.uw     =0;
    /*Lib_ccess======================================*/

    /*Lib_ascii======================================*/

    /*Lib_checksum======================================*/

    /*Lowsrc======================================*/

    /*Main======================================*/
    checkValue              =0;
    uwFkeypad               =0;
    uwFcan                  =0;
    Fkeypad_Buf             =0;
    Fcmd                    =0;
    fbase                   =0;
    vbase                   =0;
    fmin                    =0;
    fstart                  =0;
    vtemp                   =0;
    v_save                  =0;
    vcmd_ser                =0;
    mspec                   =0;
    Power_RAT               =0;
    PF_ANGLE                =0;
    IrmsRe                  =0;
    IrmsRe1                 =0;
    stall4ad                =0;
    dcbrk4ad                =0;
    OVS4ad                  =0;
    OVR4ad                  =0;
    LVS4ad                  =0;
    LVR4ad                  =0;
    LV4FAN                  =0;
    IGBT_OHLevel            =0;
    CTRLM_buf               =0;
    err_uwFfbk              =0;
    err_uwFcmd              =0;
    err_uwVout              =0;
    err_uwDcbus             =0;
    err_uwIsum              =0;
    err_uwFkey              =0;
    err_uwPower             =0;
    err_uwTorq              =0;
    err_uwMFI               =0;
    err_uwMFO               =0;
    err_uwState             =0;
    rec_uwFfbk              =0;
    rec_uwFcmd              =0;
    rec_uwVout              =0;
    rec_uwDcbus             =0;
    rec_uwIsum              =0;
    rec_uwIGBT              =0;
    rec_uwSRY               =0;
    rec_uwFault1            =0;
    rec_uwFault2            =0;
    rec_uwFault3            =0;
    rec_uwFault4            =0;
    rec_uwFault5            =0;
    rec_uwFault6            =0;
    rec_uwError1_1          =0;
    rec_uwError1_2          =0;
    rec_uwError1_3          =0;
    rec_uwError1_4          =0;
    rec_uwError2_1          =0;
    rec_uwError2_2          =0;
    rec_uwError2_3          =0;
    rec_uwError2_4          =0;
    rec_uwError3_1          =0;
    rec_uwError3_2          =0;
    rec_uwError3_3          =0;
    rec_uwError3_4          =0;
    rec_uwError4_1          =0;
    rec_uwError4_2          =0;
    rec_uwError4_3          =0;
    rec_uwError4_4          =0;
    rec_uwError5_1          =0;
    rec_uwError5_2          =0;
    rec_uwError5_3          =0;
    rec_uwError5_4          =0;
    rec_uwPWRmin            =0;
    rec_uwRUNmin            =0;
    rec_uwErrMin1           =0;
    rec_uwErrMin2           =0;
    rec_uwErrMin3           =0;
    rec_uwErrMin4           =0;
    rec_uwErrMin5           =0;
    rec_uwErrMin6           =0;
    rec_uwErrDay1           =0;
    rec_uwErrDay2           =0;
    rec_uwErrDay3           =0;
    rec_uwErrDay4           =0;
    rec_uwErrDay5           =0;
    rec_uwErrDay6           =0;
    rec_uwFkey              =0;
    rec_uwPower             =0;
    rec_uwTorq              =0;
    rec_uwMFI               =0;
    rec_uwMFO               =0;
    rec_uwState             =0;
    PrTorqueRe              =0;
    PrTorquePu              =0;
    uwDheat                 =0;
    PrDiameter              =0;
    st_uwAngle              =0;
    st_uwAbsAngle           =0;
    st_uwPGThetaM           =0;
    st_uwAnaPGInit          =0;     // Initail position detected by absolute Sin/Cos signals
    st_uwInitPos            =0;
    st_uwAnaPGInitOld       =0;     // Initail position detected by absolute Sin/Cos signals
    st_uwHallOld            =0;
    st_uwHallNew            =0;
    zcal_uwPulseErr         =0;     // PG pulse of Z pulse Calibration
    TUN_DCVolt_OK           =0;
    uwPGThetaE_COM          =0;     // [IED 1387 static Tune, 2011/07/06]
    uwPGThetaE_COM2         =0;     // [IED 1387 static Tune, 2011/07/06]
    n_period                =0;
    experiod                =0;
    cf_swCFReal             =0;
    cf_swCFSet              =0;
    cf_swOHCarry            =0;
    cf_swOLCarry            =0;     // Overload Carry Frequency
    cf_swChgTemp            =0;
    cf_step1                =0;
    cf_swCFDerate           =0;
    PTCInValue              =0;
    TorqueOut               =0;
    HS_Temp                 =0;
    IGBT_Temp               =0;
    st_swSINmean            =0;
    st_swCOSmean            =0;
    st_swSINnew             =0;
    st_swCOSnew             =0;
    st_swXout               =0;
    st_swYout               =0;
    zcal_swThetaErr         =0;     // Electrical Theta of Z pulse calibration
    uwAbsMotorHz            =0;
    zcal_uwPulseDiff        =0;
    Delay4oc                =0;
    cfstep                  =0;
    z0_cnt                  =0;
    z1_cnt                  =0;
    z2_cnt                  =0;
    GROUPTmp                =0;
    ubPGData                =0;
    TUNEPMLSLOW_V           =0;
    st_uwInterval           =0;     // StandStill falling counts
    ol_uwDeraCnt            =0;
    uwEPS_SpdLimt           =0;
    SpdMaxPu                =0;
    AVIslFunVar             =0;
    AVIslFunVar_1           =0;     //UD protocal, Bernie
    ACIslFunVar             =0;
    AUIslFunVar             =0;
    slMotorHz               =0;
    ss4                     =0;     //IODLC
    slSINsquarePu           =0;
    IR_ulTcount             =0;     //Running Dir Count
    CPUError                =0;
    Error                   =0;
    WarnCode                =0;
    PSW_CNT                 =0;
    fanoffct                =0;
    PWR_Second              =0;
    TUNErrorCnt             =0;
    PWRSaveCNT              =0;
    Cnt_ubPGWait            =0;
    Driver_ID               =0;
    mfi0_status.ub          =0;     
    mfi1_status.ub          =0;
    mfi2_status.ub          =0;
    inv_status.ub           =0;
    inv1_status.ub          =0;
    inv2_status.ub          =0;
    inv3_status.ub          =0;     // DIN function
    warn_status.ub          =0;
    com1_status.ub          =0;
    com2_status.ub          =0;
    com3_status.ub          =0;
    copy_status.ub          =0;
    lock_status.ub          =0;
    kpd1_status.ub          =0;
    kpd2_status.ub          =0;
    kpd3_status.ub          =0;
    ext_status.ub           =0;
    ext1_status.ub          =0;
    ext2_status.ub          =0;
    ext3_status.ub          =0;
    led_status.ub           =0;
    pg_status.ub            =0;
    DBC_status.ub           =0;
    Con_status.ub           =0;
    Con1_status.ub          =0;
    WREP_status.ub          =0;
    PMstart_status.ub       =0;
    exto_status.ub          =0;
    edt_status.ub           =0;
    SMTRISE_status.ub       =0;     //KEB ESD&ETS Function
    FAN_status.ub           =0;
    VH_status.ub            =0;
    WREP_status.ub          =0;     //IED 1387 static Tune
    Time_srquence.ub        =0;     //DIN time sequence
    SPD_PG_quality.ub       =0;     //PG quality function
    st_uwAbsAngleTune       =0;     //Fix state tune problem
    hsd_uwAbsAngle          =0;     //PGHSD-1 abs angle
    zcal_uwMTU1cnt          =0;     //PG count for annoy
    dir_status.uw           =0;
    err_status.uw           =0;
    cmd_status.uw           =0;
    wg_status.uw            =0;
    tun_status.uw           =0;
    key_status.uw           =0;
    pre_status.uw           =0;
    IEDPG_status.uw         =0;
    APR_status.uw           =0;
    wg_status_CC.uw         =0;     //CC Display
    tb_status.uw            =0;
    EPS_POWER_SWITCH.uw     =0;     //EPS MO Output
    Sibocom_ENflag.uw       =0;
    Sibocom_spflag.uw       =0;
    fcmd.ul                 =0;
    fcmd_vf.ul              =0;
    ftemp.ul                =0;
    fexternal.ul            =0;
    fslip.ul                =0;
    mcount.ul               =0;
    Pinput.ul               =0;
    Service_time.uw         =0;
    Star_con_status.uw      =0;
    //Main_EXT PARAM_ATTR attr[PRMAX];
    //attr.ati                =0;
    //attr.def                =0;
    //attr.max                =0;
    //attr.min                =0;
    AD2DcB1.yBias           =0;
    AD2DcB1.ksF             =0;
    AD2DcB1.ksI             =0;
    AD2DcB2.yBias           =0;     // AD to DC Bus Line 1[(x1,y1),(x2,y2)], Line 2[(x2,y2),(x3,y3)]
    AD2DcB2.ksF             =0;
    AD2DcB2.ksI             =0;
    DcB2AD1.yBias           =0;
    DcB2AD1.ksF             =0;
    DcB2AD1.ksI             =0;
    DcB2AD2.yBias           =0;
    DcB2AD2.ksF             =0;
    DcB2AD2.ksI             =0;     // DC Bus to AD Line 1[(x1,y1),(x2,y2)], Line 2[(x2,y2),(x3,y3)]
    uwVfd_Explorer_Count    =0;
    uwVfd_Explorer_Flag     =0;
    ubNew_VfdExplorerFlag   =0;
    /*Mathtool_c======================================*/
    Nh_swWn                  =0;
    Nh_swDampZ               =0;
    Nh_sltmp4                =0;
    Nh_sltmp5                =0;
    Nh_sltmp4_Old            =0;
    Nh_sltmp6_Old            =0;
    /*Modbus_dec======================================*/
    
    /*Modbus_dec_usr======================================*/

    /*Modbus_dev======================================*/
    //br_ctrl                 =0;
    /*Modbus_enc======================================*/

    /*Modbus_type======================================*/
    
    /*PH_IIC======================================*/
    cf2_index               =0;
    rtm_uw1sec              =0;
    err_uwFRAMErrRd         =0;
    rtm_ubSta1              =0;
    rtm_ubSta2              =0;
    rtm_ubInitDone          =0;
    rtm_ubTimeRd[0]         =0;
    rtm_ubTimeRd[1]         =0;
    rtm_ubTimeRd[2]         =0;
    rtm_ubTimeRd[3]         =0;
    rtm_ubTimeRd[4]         =0;
    rtm_ubTimeRd[5]         =0;
    rtm_ubTimeRd[6]         =0;
    rtm_ubTimeRd[7]         =0;
    rtm_ubTimeWr[0]         =0;
    rtm_ubTimeWr[1]         =0;
    rtm_ubTimeWr[2]         =0;
    rtm_ubTimeWr[3]         =0;
    rtm_ubTimeWr[4]         =0;
    rtm_ubTimeWr[5]         =0;
    rtm_ubTimeWr[6]         =0;
    rtm_ubTimeWr[7]         =0;
    /*PH_KeyPad======================================*/
    key_ubPageCnt           =0;
    KPDdot                  =0;
    KPDmax                  =0;
    KPDset                  =0;
    swInitPos               =0;
    RUN_sequence.uw         =0;
    /*PH_Ledkey======================================*/
    keyinx                  =0;
    keyin1                  =0;
    keyct0                  =0;
    keyct1                  =0;
    keyct2                  =0;
    keyct3                  =0;
    ledx                    =0;
    KEY_ubDispMode          =0;
    KEY_ubDispTmp           =0;
    KEY_ubWarnTmp           =0;
    disptemp                =0;
    dot                     =0;
    endct                   =0;
    spdispx                 =0;
    msg_page                =0;
    grno                    =0;
    prno                    =0;
    blinks                  =0;
    blinkf                  =0;
    blinku                  =0;
    for(i=0;i<=GRALL;i++){
        KEY_ubPrno[i]=0;
    }
    rst_det                 =0;     //reset key detecting and excuting
    relprno                 =0;
    relprno13               =0;
    userfkey                =0;
    KEY_uwPrData            =0;
    KEY_uwPWRCnt            =0;
    KEY_MioPag              =0;
    led.s0                  =0;
    led.s1                  =0;
    led.s2                  =0;
    led.s3                  =0;
    led.s4                  =0;
    led.s5                  =0;
    led.s6                   =0;
    /*PH_MFIO======================================*/
    fskip1h                 =0;
    fskip1l                 =0;
    fskip2h                 =0;
    fskip2l                 =0;
    fskip3h                 =0;
    fskip3l                 =0;
    PM_uwStart              =0;     // FOCPM start angle
    DisplayLPG              =0;     // Display LowPass Gain
    uwInitialCnt            =0;     // Initial Position Counter
    uwCAN_ChkTime           =0;     // CAN Protocol for High Cap
    MotorRUNSec             =0;
    SpDt_ubPGCard           =0;     //Modify PG Type Define
    /*PH_Rcan======================================*/

    /*PH_Usb======================================*/

    /*ProHeader======================================*/

    /*ProtectFun======================================*/
    prt_ubBFChkCnt          =0;
    prt_ubPHLCnt            =0;
    prt_ubSRYCnt            =0;
    prt_ubSRYCnt2           =0;
    prt_ubSRYrec            =0;     // SRY fault record
    prt_ubOHSCnt            =0;
    prt_ubOHRCnt            =0;
    prt_ubBRStatus          =0;
    prt_swCon1Fc            =0;
    prt_swCon2Fc            =0;
    prt_swCon3Fc            =0;
    PHLChkCNT               =0;
    FANChkCNT               =0;
    prt_uwBrkChkCnt1        =0;     
    prt_uwBrkChkCnt2        =0;
    prt_uwMcChkCnt          =0;     //Manetic Contactor Check Counter
    uwMaxDcbus              =0;
    uwMinDcbus              =0;				
    uwDeltaDcbus            =0;
    uwPHLADLevel            =0;
    uwPHLCNTsec             =0;
    prt_uwErrDT             =0;     //Error Output Delay counter
    prt_uwLVCNT             =0;
    prt_uwRatio90           =0;
    prt_uwRatio120          =0;
    prt_uwRatio180          =0;
    prt_uwRatio205          =0;
    uwIacnt                 =0;     //Output Phase Loss 2
    uwIbcnt                 =0;     //Output Phase Loss 2
    uwIccnt                 =0;     //Output Phase Loss 2
    uwIabcCnt               =0;     //Output Phase Loss 2
    uwStartMphl2cnt         =0;     //Output Phase Loss 2
    prt_uwRatio140          =0;     //modify derating function
    prt_uwRatio155          =0;
    prt_CCcnt               =0;
    prt_swPeriod            =0;
    sbk_ulWatt              =0;     // Soft brake turn on timer
    pwm_ulOL                =0;     // OL  counting value
    pwm_ulOL_C              =0;     // OL  counting value for constant torque
    ulOLCNT_C               =0;     // OL  counting level for constant torque
    prt_OLIrms.ul           =0;
    ulDeltaDcbusLPF.ul      =0;
    pwm_ulMOL.ul            =0;
    IaPuLPF.sl              =0;
    IbPuLPF.sl              =0;
    IcPuLPF.sl              =0;
    /*PR_Const======================================*/
    
    /*PR_Data======================================*/

    /*PR_Handel======================================*/
    trg_cnt                 =0;
    mfi_old                 =0;
    mfi_buf                 =0;
    mfi_status              =0;
    mfo_status              =0;
    YOnCNT                  =0;
    DOnCNT                  =0;
    DIstCNT                 =0;
    uwFaultBitCode          =0;
    uwPcomClkMI             =0;
    uwPcomDataMI            =0;
    uwSPIPcom               =0;
    swmaxT1                 =0;
    swmaxT2                 =0;
    swmaxT3                 =0;
    slmaxT1                 =0;
    slmaxT2                 =0;
    mio_ulMfiSta            =0;
    vfd_uwFunSel2.uw        =0;
    EXT_AISEL               =0;
    speed                   =0;
    acc_dec                 =0;
    YDSetBit                =0;
    YCONChkCNT              =0;
    DCONChkCNT              =0;
    MFI_TQCSel              =0;
    SPIPcomBit              =0;
    SPIPcomCNT              =0;
    MFI_ubFaultBit          =0;
    prt_ubWgEna             =0;     // add wgoff interception flag
    /*PR_LCDescript======================================*/

    /*PR_MacroEQU======================================*/

    /*PR_Motor======================================*/

    /*PR_Romdata======================================*/

    /*PR_SinTable======================================*/

    /*Rcan_et======================================*/
    can_tmo_cnt             =0;
    CAN_uwErrNo             =0;
    uwPDO_CNT               =0;
    uwPDOfailCNT            =0;
    uwPDOInCnt              =0;
    uwPDOfailBuf            =0;     //CAN fail rate function
    for(i=0;i<8;i++){
        RCAN_MB0[i]=0;
    }
    for(i=0;i<8;i++){
        RCAN_MB1[i]=0;
    }
    for(i=0;i<8;i++){
        RCAN_MB3[i]=0;
    }
    for(i=0;i<8;i++){
        RCAN_MB5[i]=0;

    }
    for(i=0;i<8;i++){
        RCAN_MB7[i]=0;
    }
    for(i=0;i<10;i++){
        RCAN_SDO_RX_MB[i]=0;
    }
    for(i=0;i<10;i++){
        RCAN_SDO_READ_MB[i]=0;
    }
    for(i=0;i<10;i++){
        RCAN_SDO_WRITE_MB[i]=0;
    }
    RCAN_ubErr4Rgst         =0;
    RCAN_Timer              =0;
    DLC_PDO_RX_TF           =0;
    DLC_PDO_TX_LTF          =0;
    DLC_PDO_TX_ALF          =0;
    RCAN_ubICTCnt           =0;
    RCAN_uwstatus           =0;
    RCAN_RX_Count           =0;
    CAN_status.uw           =0;
    DLC_PDO_RX_EM.uw        =0;
    DLC_PDO_RX_DI.uw        =0;
    DLC_PDO_TX_INV_ST.uw    =0;
    DLC_PDO_TX_INV_SPD.uw   =0;
    DLC_PDO_TX_ME.uw        =0;
    DLC_PDO_RX_RC.ub        =0;
    DLC_PDO_TX_AskC.ub      =0;
    DLC_PDO_ID004_B0.ub     =0;
    DLC_PDO_ID004_B1.ub     =0;
    DLC_PDO_ID004_B2.ub     =0;
    DLC_PDO_ID004_B3.ub     =0;
    DLC_PDO_ID004_B4.ub     =0;
    DLC_PDO_ID004_B5.ub     =0;
    DLC_PDO_ID004_B6.ub     =0;
    DLC_PDO_ID004_B7.ub     =0;
    DLC_SDO_RX_Command      =0;
    DLC_SDO_RX_Lenght       =0;
    DLC_SDO_RX_Address_H    =0;
    DLC_SDO_RX_Address_L    =0;
    DLC_SDO_RX_Data0        =0;
    UCMP_STATUS.uw          =0;     //UCMP function
    CAN_UWEST_COUNT         =0;
    CAN_UWEST_STATUS        =0;
    CAN_UWTABST0_COUNT      =0;
    CAN_UWTABST1_COUNT      =0;
    CAN_UWTABST0_STATUS     =0;
    CAN_UWTABST1_STATUS     =0;
    GK_status.ub            =0;
    /*Sbrk======================================*/
    /*SCI1_EnDat======================================*/
    edt_ubMode              =0;
    edt_ubErr               =0;
    edt_ubStep              =0;
    edt_ubRxBuf0            =0;
    edt_ubRxBuf1            =0;
    edt_ubRxBuf2            =0;
    edt_ubRxBuf3            =0;
    edt_uwEnDatTheta        =0;
    edt_uwCRCEnDat          =0;
    edt_uwCRC               =0;
    edt_uwAddr              =0;
    edt_uwPar               =0;
    /*SCI1_Hiper======================================*/
    
    /*SCI1_Remote======================================*/
    Keypad_Page3            =0;
    Keypad_PageTmp3         =0;
    COM3Err                 =0;
    PUID3Cnt                =0;
    Rx3CNT                  =0;
    Tx3CNT                  =0;
    SendCNT3                =0;
    for(i=0;i<RX_LENGTH;i++){
        RxBuf_3[i]=0;     //RX_LENGTH = 100
    }
    for(i=0;i<TX_LENGTH;i++){
        TxBuf_3[TX_LENGTH]=0;     //RX_LENGTH = 100
    }
    RTU_Silent3             =0;
    Com_WatchDog3           =0;
    SCIDIR3Flag             =0;
    SCI3_ubTXIDalay         =0;     // TXI Delay Time, Add by DINO, 03/02/2010
    SCI3_ubCNT              =0;
    SCI3_TodCNT             =0;
    RTU_CNT3                =0;
    /*SCI2_CommReg======================================*/    
    for(i=0;i<=C20MAX;i++){
        C20xx[i]=0;
    }
    for(i=0;i<=C21MAX;i++){
        C21xx[i]=0;
    }
    for(i=0;i<=C22MAX;i++){
        C22xx[i]=0;
    }
    for(i=0;i<=CALIMAX;i++){
        CFFxx[i]=0;     // address ffxx  //for calibration
    }
    for(i=0;i<=C23MAX;i++){
        KC23xx[i]=0;
    }
    for(i=0;i<=C24MAX;i++){
        Descript[i]=0;
    }
    for(i=0;i<DLCMAX;i++){
        C40xx[i]=0;
    }
    for(i=0;i<DLCMAX;i++){
        DLCxx[i]=0;
    }
    uwElecAngle             =0;
    ubpage                  =0;     //[User page reserve jump, Bernie, 08/05/2011]         
    /*SCI3_Remote======================================*/
    Keypad_Page             =0;
    Keypad_PageTmp          =0;
    COM2Err                 =0;
    PUID2Cnt                =0;
    MFD_page                =0;
    Rx2CNT                  =0;
    Tx2CNT                  =0;
    SendCNT2                =0;
    for(i=0;i<RX_LENGTH;i++){
        RxBuf_2[i]=0;     //RX_LENGTH = 100
    }
    for(i=0;i<TX_LENGTH;i++){
        TxBuf_2[i]=0;     //RX_LENGTH = 100
    }
    RTU_Silent2             =0;
    Com_WatchDog2           =0;
    SCIDIR2Flag             =0;
    SCI2_ubTXIDalay         =0;     // TXI Delay Time, Add by DINO, 03/02/2010
    SCI2_ubCNT              =0;
    SCI2_TodCNT             =0;
    RTU_CNT2                =0;
    /*SCI4_PGComm======================================*/
    
    /*SCI_IntPro======================================*/
    /*Stacksct======================================*/
    /*Switch======================================*/
    /*SYSInit======================================*/
    /*TB_100us======================================*/
    TB_uw100usCnt           =0;
    TB_uwPg_Cnt             =0;
    /*TB_1ms======================================*/
    TB1_ub1msCnt            =0;
    TB1_ub100msCnt          =0;
    TB1_ub1secCnt           =0;
    TB1_ub500usCnt          =0;
    TB1_ubOverWsCnt         =0;
    TB1_ubErrCnt            =0;     // Error detect delay time when power on
    TB1_ubFOCPGSerCnt       =0;
    TB1_MPHL_Buf            =0;     
    ubPDO_TxCNT             =0;     // CAN Protocol for High Cap 
    TB1_uwSTOErrCnt         =0;
    EPS_btDirect            =0;
    OLDelayT                =0;
    OLSEL                   =0;
    saf_uwPGF5_Type         =0;
    PIDFcmd                 =0;
    PID_LPG                 =0;
    AFMOut[0]               =0;
    AFMOut[1]               =0;    
    AFMOut[2]               =0;
    uwIsDtL                 =0;
    PGScaleDataTmp          =0;
    PGScaleData             =0;
    TB1_uwSTORSETCnt        =0;
    TB1_uwSTObRESETCnt        =0;
    TB1_uwSTOARESETCnt        =0;
    uw_STOStatus            =0;
    uw_STOStatusOld         =0;
    uwSIN_data              =0;
    uwCOS_data              =0;
    TB1_uwBrkRunCnt         =0;
    TB1_uwBrkStopCnt        =0;
    TB1_uwPIDLossCnt        =0;
    TB1_uwPIDDeviCnt        =0;
    TB1_uwSleepCnt          =0;
    TB1_uwCCCnt             =0;
    TB1_uwFanCnt            =0;
    TB1_uwFanCnt1           =0;
    TB1_uwMCRunCnt          =0;
    TB1_uwMCStopCnt         =0;
    TB1_uwSBKCnt            =0;
    TB1_uwRYCnt             =0;
    TB1_uwOLCnt             =0;
    TB1_uwOT1Cnt            =0;
    TB1_uwOT2Cnt            =0;
    TB1_uwLVCnt             =0;
    TB1_uwBBCnt             =0;
    TB1_uwDCICnt            =0;
    TB1_uwKEBRtCnt          =0;
    TB1_uw0p5secCnt         =0;
    TB1_uwMaxFout           =0;
    TB1_uwNewIrmsAD         =0;
    uwEPScnt                =0;
    uwSt1387cnt             =0;     //IED 1387 static Tune 
    uwEPS_Delay_CNT         =0;
    uwEPS_Off_CNT           =0;
    TB1_uw1secCnt           =0;
    TB1_uwStarConRunCnt     =0;
    TB1_uwStarConStopCnt    =0;
    PIDinteg_rem            =0;
    PIDintegral             =0;
    PID_slofsetv            =0;
    accel_error             =0;
    decel_error             =0;
    piderr                  =0;
    piderr_Z1               =0;
    TB1_swCosphi            =0;
    cosphi_z1               =0;
    delta_cosphi            =0;
    TQRCMemswPer            =0;
    TB1_swMPHLcnt           =0;
    TB1_swMPHLstep          =0;
    TB1_swTempcnt           =0;
    TB1_swTemp1             =0;
    TB1_swTemp2             =0;
    TB1_swTemp3             =0;
    TB1_slSpdSerPu          =0;
    cosphiLPF.sl            =0;
    TH1adLPF.sl             =0;
    TH2adLPF.sl             =0;
    AVIadLPF.sl             =0;
    ACIadLPF.sl             =0;
    AUIadLPF.sl             =0;
    PTCInLPF.sl             =0;
    GFFadLPF.sl             =0;
    SINadLPF.sl             =0;
    COSadLPF.sl             =0;
    PGLadLPF.sl             =0;
    facc1.ul                =0;
    facc2.ul                =0;
    facc3.ul                =0;
    facc4.ul                =0;
    fdec1.ul                =0;
    fdec2.ul                =0;
    fdec3.ul                =0;
    fdec4.ul                =0;
    fjacc.ul                =0;
    fjdec.ul                =0;
    fdec5.ul                =0;
    fdec_ESD.ul             =0;
    facc.ul                 =0;
    fdec.ul                 =0;
    sacc.ul                 =0;
    sdec.ul                 =0;
    sdec_old.ul             =0;
    sdec_tmp.ul             =0;
    fdec_t2.ul              =0;
    PIDoutf.ul              =0;
    TB1_ulSpdtempPu.ul      =0;
    Pfdec.ul                =0;
    TB1_CmdRpm.ul           =0;
    VFfslip_uwLPG           =0;
    cosphi_uwLPG            =0;
    VFVcomp_uwLPG           =0;
    AUI1In_LPG              =0;
    ACIIn_LPG               =0;
    EPS_DIRtemp             =0;
    AUI2In_LPG              =0;
    PTCIn_LPG               =0;
    dcbusLPG                =0;
    PHL_LPG                 =0;
    CurZero_LPG             =0;
    APP01_uwSO1             =0;
    APP01_uwSO2             =0;
    EPS_swRecord_S1         =0;
    EPS_swRecord_CNT        =0;
    EPS_swRecord_AVG        =0;
    EPS_swRecord_up         =0;
    EPS_swRecord_dw         =0;
    AUI_swoffset            =0; //[Pre-Torque with Load-Cell,Lyabryan,2019/01/08]
    AUI_swgain              =0; //[Pre-Torque with Load-Cell,Lyabryan,2019/01/08]
    AUI_swem_V              =0; //[Pre-Torque with Load-Cell,Lyabryan,2019/01/08]
    AUI_swem_T              =0; //[Pre-Torque with Load-Cell,Lyabryan,2019/01/08]
    AUI_swfl_V              =0; //[Pre-Torque with Load-Cell,Lyabryan,2019/01/08]
    AUI_swfl_T              =0; //[Pre-Torque with Load-Cell,Lyabryan,2019/01/08]
    TB1_uwPhi               =0;
    Zphase_countAB_count    =0;
    Zphase_countAB_flag     =0;
    Zphase_countAB_old      =0;
    Zphase_error_zero       =0;
    Zphase_tune_count       =0;
    Zphase_swcountAB_error  =0;
    Zphase_swcountAB_error_old  =0;
    dec_integral            =0;
    acc_integral            =0;
    TB1_slSpdAcc            =0;
    acc1_integral           =0;
    reg_t2s3TCR             =0;
    PGHOMEMem               =0;
    MI_INVMem               =0;
    MO_INVMem               =0;
    uwOverWsL               =0;
    uwAFMda                 =0;
    TB1_uwGencnt            =0;
    uwFWDPFangle            =0;
    uwREVPFangle            =0;
    TB1_uwFcmdOld           =0;
    Vcmd_LL2                =0;
    uwRetryCnt              =0;
    uwRetryTimeCnt          =0;
    rec_uwRetryCnt          =0;
    uwReset_10mCnt          =0;
    TB1_uwGenorMotCnt       =0;
    GearAccCnt              =0;
    GearDecCnt              =0;
    speed_tmp               =0;
    fhunt.sl                =0;
    IqseOutPuLPF.sl         =0;
    DcbusDCLPF2.sl          =0;
    VcmdLLPF2.sl            =0;
    VF_IqseOutPuLPF.sl      =0;
    STO_FLAG                =0;
    STO_FLAG2               =0;
    uwAcc10msCount          =0;
    uwWritePrCnt            =0;
    Run_Time_srquence.uw    =0;
    RST_Status.ub           =0;
    sl_IqErrKp              =0;
    sl_IqErrKp6             =0;
    slFdbOld                =0;
    slFdbErr                =0;
    swErrTEST               =0;
    ubPGrevCnt              =0;
    ubRevise                =0;
	uwGFF_MaxVal			=0;	// GFF Maximum Value Record, Jerry Yu, 2019/11/11
	ubIntervalSeted			=0;		//[Add GFF and Ocx auto reset function, Jerry Yu, 2019/05/23]

    OPHL_swIqss             =0;
    OPHL_swIdss             =0;
    OPHL_swIqss_cmd         =0;
    OPHL_swIdss_cmd         =0;
    OPHL_swCur_err          =0;

    OPHL_uwTheta            =0;
    OPHL_uwTheta_Z1         =0;
    OPHL_uwDeltaTheta       =0;
    OPHL_uwDeltaTheta_Filter=0;

    OPHL_swEst_Sp_Filter    =0;
    OPHL_swEst_Sp_Filter_Z1 =0;
    OPHL_swEst_Sp_Error     =0;
    OPHL_swEst_Err_Cnt      =0;
    OPHL_swEst_Err_State    =0;
    OPHL_swEst_Det_Delay    =0;
    OPHL_swCur_err_Filter   =0;
    OPHL_swCur_err_Limit    =0;









    
    /*TB_WG======================================*/
    
    /*Typedefine======================================*/
    
    /*USB_CDC======================================*/
    
    /*Vect======================================*/
    
    /*VecTtb1======================================*/
    
    /*Version======================================*/
}

#ifndef _INITIAL_VAR
	#undef _INITIAL_VAR
#endif

