/***********************************************************************/
/*                                                                     */
/*  FILE        :stacksct.h                                            */
/*  DATE        :Wed, Jul 31, 2013                                     */
/*  DESCRIPTION :Setting of Stack area                                 */
/*  CPU TYPE    :RX63T                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.51).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
#pragma stacksize su=0x500      
#pragma stacksize si=0x500      
